name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # Har 5 minute me chalega (UTC time)
  workflow_dispatch: {}     # Manual trigger bhi chalega

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Render server
        run: |
          curl -I https://auto-spin-bot-lt7x.onrender.com || true
